#!/usr/bin/env bash
set -e

IMG_DIR=tmp_figures
if [ $(ls -1 ./$IMG_DIR/*.png 2>/dev/null | wc -l) != 0 ]; then
    echo "Deleting files"
    rm ./$IMG_DIR/*.png
fi

docker-compose run app python main.py $@
